# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Nightly Fuzz
on:
  schedule:
    # Nightly at midnight -- uses UTC, so 7am.
    - cron:  '0 7 * * *'
  # This lets us trigger manually from the UI.
  workflow_dispatch:

jobs:
  build:
    name: Nightly Fuzz
    runs-on:
      labels: ubuntu-22.04-64core
    steps:
      - uses: actions/checkout@v2

      # We don't use action/cache nighlty workflows to ensure full reproducibility of the build.

      - name: Install dependencies via apt
        run: sudo apt-get install python3-distutils python3-dev python-is-python3 libtinfo5  build-essential liblapack-dev libblas-dev gfortran

      - name: Bazel Build Fuzz Driver (opt)
        run: |
          bazel build -c opt --noshow_progress xls/fuzzer:run_fuzz_multiprocess

      - name: Bazel Run Fuzz (opt)
        run: |
          bazel run -c opt xls/fuzzer:run_fuzz_multiprocess -- --crash_path "${GITHUB_WORKSPACE}/crashers" --sample_count=2048 --summary_path "${GITHUB_WORKSPACE}/crashers"

      - name: Upload Fuzz Crashers
        uses: actions/upload-artifact@v2
        with:
          name: crashers
          path: "${GITHUB_WORKSPACE}/crashers"
