# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Nightly MacOS
on:
  schedule:
    # Nightly at midnight -- uses UTC, so 7am.
    - cron:  '0 7 * * *'
  # This lets us trigger manually from the UI.
  workflow_dispatch:

jobs:
  build:
    name: Bazel Build (opt)
    runs-on:
      labels: macos-latest-xlarge
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2

      # We don't use action/cache nighlty workflows to ensure full reproducibility of the build.

      - name: Bazel Build Tools (opt)
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build -c opt --test_output=errors -- //xls/dslx:interpreter_main //xls/dslx/ir_convert:ir_converter_main //xls/tools:opt_main //xls/tools:codegen_main
