# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# See also: https://github.com/marketplace/actions/bazel-action

name: Solo Bazel Test (Ubuntu 22.04)

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Bazel Target Pattern'
        default: '//xls/dslx:interpreter_test'
        required: true
      runs_per_test:
        description: 'Number of Runs'
        default: '1'
        required: true

env:
  BAZEL_TARGET: ${{ github.event.inputs.target }}
  BAZEL_RUNS_PER_TEST: ${{ github.event.inputs.runs_per_test }}

jobs:
  build:
    name: Bazel Test (opt)
    runs-on:
      labels: ubuntu-22.04-64core
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2

      - name: Mount Bazel Cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          # Create/use a cache called bazel-cache-22_04-<commit hash>
          # and read the latest cache with prefix bazel-cache-22_04-
          # if it doesn't already exist.
          key: bazel-cache-22_04-${{ github.sha }}
          restore-keys: bazel-cache-22_04-

      - name: Install dependencies via apt
        run: sudo apt-get install python3-distutils python3-dev python-is-python3 libtinfo5  build-essential liblapack-dev libblas-dev gfortran

      - name: Bazel Test Target (opt)
        run: |
          bazel test -c opt --test_output=all --runs_per_test=$BAZEL_RUNS_PER_TEST -- $BAZEL_TARGET
